Map<int, String> errors = {
  11: "Aucun utilisateur n'a été trouvé pour cet e-mail",
  12: "Mot de passe incorrect",
  13: "L'adresse électronique n'est pas valide",
  14: "L'adresse électronique saisie a été désactivée",
  15: "Erreur ! Vérifiez votre connexion internet et réessayez",
  16: "Erreur ! Veuillez réessayer",
  17: "Le mot de passe fourni est trop faible",
  18: "Le compte existe déjà pour cet e-mail",
  19: "Votre compte a été désactivé",
  20: "Le compte existe déjà avec un identifiant différent",
  21: "Une erreur s'est produite lors de l'accès aux informations d'identification. Réessayez",
  22: "Une erreur s'est produite lors de l'utilisation de Google Sign In. Réessayez.",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
};
